### PR TITLE
2021 updates

### PR DESCRIPTION
**Pull request by MabezDev**

### CODE REVIEW

**Comment by RCasatta** [comment]
What's stopping this to be merged and released?
Thanks

**Comment by MabezDev** [comment]
@RCasatta the primary reason is that I have not yet tested this on any hardware so I don't know if it actually works.

**Comment by RCasatta** [comment]
I did and it looks it's working

**Comment by MabezDev** [comment]
Awesome! Thanks for testing!

**Comment by MabezDev** [comment]
v3.0.0 released on crates.io :)

**Pull request merged**
