### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ivmarkov**
Most important is the update of `embedded-graphics-core` to 0.4

The rest of the updates - I must say - I could not test.

### CODE REVIEW

**Comment by MabezDev** [comment]
I no longer had readily available access to one of these displays, could @tmbull or @bentwire give this a try?

**Comment by tmbull** [comment]
It probably won't be until  Monday, but I can give it a try.

**Comment by tmbull** [comment]
So I was able to test this code today by cloning @ivmarkov's branch and building my project against it. It seems to work fine. No compile errors, and everything seems to function as expected.

TBH, I am not sure how to verify the `dev-dependencies` or when they would even be used. I don't see any tests or examples in the repo. I also don't have an `stm32-l4xx` chip to test against anyway. I only have arduino and stm32-f401 ATM. If the `dev-dependencies` are no longer referenced anywhere in code, I would suggest removing them entirely.

**Comment by ivmarkov** [comment]
I think we should:
* Remove the dev dependencies, as there are no tests/examples (yet)
* Remove `memory.x`
* Remove the profiles
* Update the crate rust to 2021

If everybody is fine with that, I can update the PR.

**Comment by ivmarkov** [comment]
> I think we should:
> 
> * Remove the dev dependencies, as there are no tests/examples (yet)
> * Remove `memory.x`
> * Remove the profiles
> * Update the crate rust to 2021
> 
> If everybody is fine with that, I can update the PR.

I've done ^^^.
Additionally, I took the freedom to run `cargo fmt` and `cargo clippy` on the code, hence the large changeset.
We probably need a simplistic CI as well, but perhaps a separate PR.

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
